image: docker:latest
services:
  - docker:dind

run-examples1:
  script:
  - cat /proc/cpuinfo
  - cat /etc/os-release
  - apk update
  - apk add sudo  
  - sudo apk install git
  - git --version
  - df -h --output='size','pcent' \
  - /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'
  - earthly -P +examples1

run-examples2:
  dependencies: [run-examples1]
  script:
  - cat /proc/cpuinfo
  - cat /etc/os-release
  - apk update
  - apk add sudo  
  - sudo apk install git
  - git --version
  - df -h --output='size','pcent' \
  - /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'
  - earthly -P +examples2
