# dist: alpine
# install:
#   - "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.8/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
# script: cat /etc/*-release && earthly ./examples/c+build

language: c

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-base cmake cunit-dev

script:
  - cd ./examples/c
  - cmake test
  - make

#       - run:
#           name: Installing SUDO
#           command: 'apk update && apk add sudo
#       - run:
#           name: Installing GCC
#           command: 'apk update && apk add gcc g++'
#       - run:
#           name: Install build-base and make and cunit-dev
#           command: sudo apk --update add build-base cmake cunit-dev
#       - run:
#           name: Creating Build Files
#           command: 'cd ./examples/c/ && cmake test'
#       - run:
#           name: Run Make
#           command: cd ./examples/c && make
#       - run:
#           name: Run Unit Tests
#           command: ./examples/c/unit-test 