
install:
  - "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.8/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

jobs:
  include:
    - stage: test
      script: earthly ./examples/c+unit-test
    - stage: build
      script: earthly ./examples/c+build




# language: c

# compiler:
#   - gcc

# jobs:
#   include:
#     - stage: test
#       addons:
#         apt:
#           update: true
#           packages:
#           - cmake
#           - libcunit1-dev
#       script:
#         - cd ./examples/c
#         - cmake test
#         - make
#         - ./unit-test
#     - stage: build
#       addons:
#         apt:
#           update: true
#           packages:
#           - cmake
#           - build-essential
#       script:
#         - cd ./examples/c
#         - cmake src
#         - make

