# dist: alpine
# install:
#   - "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.8/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
# script: cat /etc/*-release && earthly ./examples/c+build

language: c

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
    - cmake
    - libcunit1-dev

script:
  - cd ./examples/c
  - cmake test
  - make
  - ./unit-test 
